# Generated by Django 4.0.3 on 2022-03-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_emprestimo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprestimo',
            new_name='Emprestimos',
        ),
    ]
