# Generated by Django 4.0.3 on 2022-03-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_alter_emprestimos_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
