# Generated by Django 4.0.3 on 2022-03-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=3, max_length=254),
            preserve_default=False,
        ),
    ]
